### ISSUE TITLE
Create a requirements.txt to lock packages and download

### ISSUE THREAD

**Issue by ketphan02** [bohuie/collabAnalysis#6]

**Comment by bohuie** [comment]
Can you help with this? We might not have the experience to do this. Perhaps in a few weeks, we can refactor and do this together? What do you think?

**Comment by apinchbeck** [comment]
@bohuie I can get on this asap. It's not difficult and I've done it before. Especially using command line it's really simple

**Comment by bohuie** [comment]
Okay but you need to finish your current tasks first as a priority. I don't want you to get distracted with other things right now.

**Comment by apinchbeck** [comment]
It honestly took me 10 mins. It's really fast to do with pipreqs from the command line. The PR is open now, and I can update it as we go along (again, pipreqs does this for me, I just need to run it every once in awhile to update the file).
