### ISSUE TITLE
Do we need files/json?

### ISSUE THREAD

**Issue by ketphan02** [bohuie/collabAnalysis#7]
The folder might make the repo bulky overtime without contributing much, we can set up something else to store this

**Comment by bohuie** [comment]
We will store the data extracted from repos so we can work on them. We are thinking of having a data/ folder but now it's called files/. In addition to a json/ subdirectory, we might also have a csv/ to store csv formatted files. What do you think? Is there another structure that works better?

**Comment by bohuie** [comment]
I don't believe that's true in the long term we don't need it. I think we should keep it and keep track of what we scrape.

**Comment by apinchbeck** [comment]
> I don't believe that's true in the long term we don't need it. I think we should keep it and keep track of what we scrape.

Sounds good! I'm going to close this issue then. However, I will make sure to switch the "files" over to "data"
